# Generated by Django 4.0.2 on 2022-03-05 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('sell-only', 'Sell Only'), ('sell-trade', 'Sell & Trade'), ('trade-only', 'Trade Only')], max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('account_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
                ('is_avalabile', models.BooleanField(default=True, max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('approved', models.BooleanField(default=False, max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Trade_Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('account_email', models.CharField(max_length=200, unique=True)),
                ('account_password', models.CharField(max_length=200, unique=True)),
                ('account_title', models.CharField(max_length=200)),
                ('account_platform', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False, max_length=20)),
                ('answer', models.BooleanField(default=False, max_length=20)),
                ('account_owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_review', models.FloatField(default=0)),
                ('review_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
