# Generated by Django 4.0.2 on 2022-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_requests',
            name='approved',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
